//! Pure stargate reachability engine over a static k-space adjacency map
//! (spec "Reachability", `.scratch/esi-intel-feeds/spec.md`; ticket
//! `.scratch/esi-intel-feeds/issues/04-stargate-reachability-and-sov-timers-board.md`).
//!
//! [`StargateGraphFile`] is the on-disk shape of `config/stargates.json`,
//! generated by `src/bin/build_stargate_graph.rs` from the SDE
//! `mapSolarSystemJumps` table (see that binary's doc comment for the
//! refresh procedure). [`StargateGraph`] is the pure in-memory adjacency
//! map; [`Reachability`] is one breadth-first search result from a single
//! origin.
//!
//! Nothing in this module touches the network or a database: loading the
//! file is the only IO, isolated in [`load_stargate_graph_file`] so the
//! BFS itself stays unit-testable without a filesystem. `Reachability`'s
//! `extra_edges` parameter went unused by every caller in ticket 04
//! (stargates only); ticket 05's `crate::sov_feed::chain::DynamicChainSovReachability`
//! is exactly the caller this shape was designed for -- it merges the
//! current Wanderer chain's traversable connections in and calls
//! `compute` again, with no change required to this module at all.

use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap, VecDeque};
use std::path::Path;

/// Default location of the generated stargate graph, relative to the
/// process's working directory (same convention as `config/systems.json`
/// and friends in `src/config.rs`).
pub const DEFAULT_STARGATE_GRAPH_PATH: &str = "config/stargates.json";

/// The on-disk shape of `config/stargates.json`: an undirected adjacency
/// map (both directions present for every stargate connection) plus
/// provenance for the SDE snapshot it was generated from. `adjacency` uses
/// a `BTreeMap` rather than a `HashMap` so a regenerated file diffs
/// cleanly (deterministic key order) and so this same type serves as both
/// the serialized form and [`StargateGraph`]'s internal representation.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct StargateGraphFile {
    /// Fuzzwork SDE dump identifier (e.g. `eve_3480926_20260826_134500`,
    /// parsed from the dump directory listing) or, when that identifier
    /// could not be discovered, a `last-modified:` fallback -- see
    /// `src/bin/build_stargate_graph.rs`.
    pub sde_version: String,
    /// `Last-Modified` response header on the source CSV, when present.
    #[serde(default)]
    pub source_last_modified: Option<String>,
    pub generated_at: chrono::DateTime<chrono::Utc>,
    pub system_count: usize,
    pub edge_count: usize,
    pub adjacency: BTreeMap<i64, Vec<i64>>,
}

/// Why [`load_stargate_graph_file`] could not produce a graph. Never
/// panics; every variant is a normal `Result::Err` the caller degrades
/// from (spec: "fails loudly" means logged, not a process exit -- see
/// `src/lib.rs`'s sov reachability wiring).
#[derive(Debug)]
pub enum StargateGraphLoadError {
    Io(std::io::Error),
    Parse(serde_json::Error),
}

impl std::fmt::Display for StargateGraphLoadError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "could not read stargate graph file: {error}"),
            Self::Parse(error) => {
                write!(formatter, "could not parse stargate graph file: {error}")
            }
        }
    }
}

impl std::error::Error for StargateGraphLoadError {}

/// Reads and parses `config/stargates.json` (or an arbitrary `path`, for
/// tests). The only IO in this module.
pub fn load_stargate_graph_file(path: &Path) -> Result<StargateGraphFile, StargateGraphLoadError> {
    let bytes = std::fs::read(path).map_err(StargateGraphLoadError::Io)?;
    serde_json::from_slice(&bytes).map_err(StargateGraphLoadError::Parse)
}

/// The pure, in-memory k-space stargate graph: an undirected adjacency map
/// (every edge appears in both directions). No IO.
#[derive(Clone, Debug)]
pub struct StargateGraph {
    adjacency: BTreeMap<i64, Vec<i64>>,
    pub sde_version: String,
}

impl StargateGraph {
    pub fn from_file(file: StargateGraphFile) -> Self {
        Self {
            adjacency: file.adjacency,
            sde_version: file.sde_version,
        }
    }

    /// Builds a graph directly from an edge list, symmetrizing it (both
    /// directions added regardless of the input order). Test-only: real
    /// graphs are always loaded from `config/stargates.json`.
    #[cfg(test)]
    pub fn from_edges(sde_version: impl Into<String>, edges: &[(i64, i64)]) -> Self {
        let mut adjacency: BTreeMap<i64, Vec<i64>> = BTreeMap::new();
        for &(a, b) in edges {
            adjacency.entry(a).or_default().push(b);
            adjacency.entry(b).or_default().push(a);
        }
        Self {
            adjacency,
            sde_version: sde_version.into(),
        }
    }

    pub fn system_count(&self) -> usize {
        self.adjacency.len()
    }

    /// Undirected edge count (each stargate connection counted once, even
    /// though it appears twice in `adjacency`).
    pub fn edge_count(&self) -> usize {
        self.adjacency.values().map(Vec::len).sum::<usize>() / 2
    }

    fn neighbors(&self, system: i64) -> &[i64] {
        self.adjacency
            .get(&system)
            .map(Vec::as_slice)
            .unwrap_or(&[])
    }

    /// Whether a real stargate connects `a` and `b` directly (order
    /// doesn't matter -- the graph is undirected). Used by
    /// `crate::sov_feed::chain::build_chain_graph_variant` (ticket 05) so
    /// a Wanderer connection that merely duplicates an already-real
    /// stargate (a map operator manually tracking a normal gate route)
    /// does not get counted as a chain-provenance edge: the stargate
    /// already provides that jump, so the BFS's choice of which parallel
    /// edge it "used" would otherwise be an implementation detail leaking
    /// into `via_chain`.
    pub fn has_edge(&self, a: i64, b: i64) -> bool {
        self.neighbors(a).contains(&b)
    }
}

/// One breadth-first search result from a single origin ("home system"):
/// jump distance and predecessor for every system the search reached.
/// Computed once at start-up (or, later, once per chain snapshot) and
/// reused for every campaign a collection cycle evaluates -- BFS over the
/// whole graph is cheap (a few thousand nodes) compared to running it per
/// campaign.
#[derive(Clone, Debug)]
pub struct Reachability {
    home: i64,
    jumps: HashMap<i64, u32>,
    predecessor: HashMap<i64, i64>,
}

impl Reachability {
    /// Runs BFS from `home` over `graph` plus `extra_edges` (undirected,
    /// added in both directions). `extra_edges` is empty for every caller
    /// in this ticket; ticket 05 passes Wanderer chain connections here
    /// without needing any other change to this type.
    pub fn compute(graph: &StargateGraph, home: i64, extra_edges: &[(i64, i64)]) -> Self {
        let mut extra: HashMap<i64, Vec<i64>> = HashMap::new();
        for &(a, b) in extra_edges {
            extra.entry(a).or_default().push(b);
            extra.entry(b).or_default().push(a);
        }

        let mut jumps: HashMap<i64, u32> = HashMap::new();
        let mut predecessor: HashMap<i64, i64> = HashMap::new();
        jumps.insert(home, 0);
        let mut queue = VecDeque::new();
        queue.push_back(home);

        while let Some(current) = queue.pop_front() {
            let current_jumps = jumps[&current];
            let extra_neighbors = extra.get(&current).map(Vec::as_slice).unwrap_or(&[]);
            for &next in graph.neighbors(current).iter().chain(extra_neighbors) {
                if let std::collections::hash_map::Entry::Vacant(entry) = jumps.entry(next) {
                    // Non-panicking arithmetic: a real graph's diameter
                    // never approaches u32::MAX, but saturating rather
                    // than wrapping keeps this true by construction even
                    // for a pathological synthetic graph in a test.
                    entry.insert(current_jumps.saturating_add(1));
                    predecessor.insert(next, current);
                    queue.push_back(next);
                }
            }
        }

        Self {
            home,
            jumps,
            predecessor,
        }
    }

    pub fn home(&self) -> i64 {
        self.home
    }

    /// Shortest jump count to `target`, or `None` if it is unreachable
    /// from home over this graph (a J-space system, or one in an
    /// unconnected pocket).
    pub fn jumps(&self, target: i64) -> Option<i64> {
        self.jumps.get(&target).copied().map(i64::from)
    }

    /// Whether `target` is reachable in at most `max_jumps` jumps.
    /// Non-panicking for any `max_jumps` value, including one a caller
    /// forgot to validate: a negative bound simply matches nothing rather
    /// than under/overflowing the comparison.
    pub fn is_reachable_within(&self, target: i64, max_jumps: i64) -> bool {
        match self.jumps(target) {
            Some(jumps) => max_jumps >= 0 && jumps <= max_jumps,
            None => false,
        }
    }

    /// The system-ID route from home to `target` inclusive, in travel
    /// order, or `None` when `target` is unreachable. The walk is bounded
    /// by the number of known systems so a corrupt predecessor map (which
    /// should never occur -- `compute` only ever records a predecessor
    /// once per system, before enqueuing it) can never loop forever
    /// instead of returning `None`.
    pub fn path(&self, target: i64) -> Option<Vec<i64>> {
        if !self.jumps.contains_key(&target) {
            return None;
        }
        let mut route = vec![target];
        let mut current = target;
        let max_len = self.jumps.len().saturating_add(1);
        while current != self.home {
            let previous = *self.predecessor.get(&current)?;
            current = previous;
            route.push(current);
            if route.len() > max_len {
                return None;
            }
        }
        route.reverse();
        Some(route)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Turnur (30002086) and one of its real stargate neighbours, per the
    /// generated `config/stargates.json` (spot-checked against the SDE
    /// `mapSolarSystemJumps` CSV directly: Turnur's k-space neighbours are
    /// Uisper, Aset, Isbrabata, and Zarzakh).
    const TURNUR: i64 = 30_002_086;
    const UISPER: i64 = 30_002_083;
    /// A real J-space (wormhole) system ID: wormhole systems have no
    /// stargates, so this can never appear in `mapSolarSystemJumps` and is
    /// guaranteed absent from the generated graph.
    const J_SPACE_SYSTEM: i64 = 31_000_005;

    fn real_graph() -> StargateGraph {
        let file = load_stargate_graph_file(Path::new(DEFAULT_STARGATE_GRAPH_PATH))
            .expect("config/stargates.json is generated and committed");
        StargateGraph::from_file(file)
    }

    #[test]
    fn bfs_finds_the_known_gate_distance_from_turnur_to_a_real_neighbour() {
        let graph = real_graph();
        let reachability = Reachability::compute(&graph, TURNUR, &[]);
        assert_eq!(reachability.jumps(UISPER), Some(1));
        assert_eq!(reachability.path(UISPER), Some(vec![TURNUR, UISPER]));
    }

    #[test]
    fn bfs_returns_none_for_an_unreachable_j_space_system() {
        let graph = real_graph();
        let reachability = Reachability::compute(&graph, TURNUR, &[]);
        assert_eq!(reachability.jumps(J_SPACE_SYSTEM), None);
        assert_eq!(reachability.path(J_SPACE_SYSTEM), None);
        assert!(!reachability.is_reachable_within(J_SPACE_SYSTEM, 11));
    }

    #[test]
    fn is_reachable_within_respects_the_exact_boundary() {
        // Synthetic linear chain: 1 -> 2 -> 3 -> 4 -> 5 (4 jumps from 1 to 5).
        let graph = StargateGraph::from_edges("test", &[(1, 2), (2, 3), (3, 4), (4, 5)]);
        let reachability = Reachability::compute(&graph, 1, &[]);
        assert_eq!(reachability.jumps(5), Some(4));
        assert!(reachability.is_reachable_within(5, 4));
        assert!(!reachability.is_reachable_within(5, 3));
        // Non-panicking for a nonsensical negative bound.
        assert!(!reachability.is_reachable_within(5, -1));
    }

    #[test]
    fn extra_edges_shortcut_reduces_the_jump_count_and_the_path() {
        let graph = StargateGraph::from_edges("test", &[(1, 2), (2, 3), (3, 4), (4, 5)]);
        let without_shortcut = Reachability::compute(&graph, 1, &[]);
        assert_eq!(without_shortcut.jumps(5), Some(4));

        let with_shortcut = Reachability::compute(&graph, 1, &[(1, 5)]);
        assert_eq!(with_shortcut.jumps(5), Some(1));
        assert_eq!(with_shortcut.path(5), Some(vec![1, 5]));
    }

    #[test]
    fn from_edges_builds_a_symmetric_undirected_graph() {
        let graph = StargateGraph::from_edges("test", &[(1, 2)]);
        assert_eq!(graph.system_count(), 2);
        assert_eq!(graph.edge_count(), 1);
        let reachability = Reachability::compute(&graph, 2, &[]);
        assert_eq!(reachability.jumps(1), Some(1));
    }

    #[test]
    fn has_edge_is_order_independent_and_false_for_a_missing_edge() {
        let graph = StargateGraph::from_edges("test", &[(1, 2)]);
        assert!(graph.has_edge(1, 2));
        assert!(graph.has_edge(2, 1));
        assert!(!graph.has_edge(1, 3));
        assert!(!graph.has_edge(3, 4));
    }

    #[test]
    fn load_stargate_graph_file_reports_a_missing_file() {
        let error = load_stargate_graph_file(Path::new("config/does-not-exist.json"))
            .expect_err("missing file is an error, not a panic");
        assert!(matches!(error, StargateGraphLoadError::Io(_)));
    }

    #[test]
    fn load_stargate_graph_file_reports_malformed_json() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let path = dir.path().join("stargates.json");
        std::fs::write(&path, b"not json").expect("write malformed fixture");
        let error =
            load_stargate_graph_file(&path).expect_err("malformed JSON is an error, not a panic");
        assert!(matches!(error, StargateGraphLoadError::Parse(_)));
    }
}
