#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# This wizard drives the seven-day, non-pinging pilot of the sovereignty
# timer and watchlist feeds described in
#   .scratch/esi-intel-feeds/issues/11-deploy-and-verify-the-pilot.md
# and the runbook docs/sov-and-watchlist-feeds.md.
#
# It is READ-ONLY against PostgreSQL (SELECT only; the one exception is the
# read-only pg_dump backup in step 1). It never sends Discord messages, never
# calls ESI, never edits .env / docker-compose.yaml, and never runs
# `docker compose up/down/restart` itself — it PROMPTS the operator to perform
# restarts and slash commands, then verifies. It writes evidence only to
# docs/rollouts/esi-intel-feeds-pilot.md and this run's state file.
#
# The pilot spans seven days with deliberate restarts on days 2 and 5, so the
# steps are NOT a straight line: run the wizard with no argument for a menu of
# steps (each shows its recorded status and can be re-run), or non-interactively
# as `esi-intel-feeds-pilot.sh <step-number>` / `esi-intel-feeds-pilot.sh sample`.
# State persists in docs/rollouts/.esi-intel-feeds-pilot.state so a re-run
# resumes exactly where you left off. (Deviation from the linear template noted
# in the wizard header above and in the rollout artifact.)

TOTAL_STAGES=12
umask 077

# Anchor at the repo root regardless of the caller's working directory.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO=$(cd "$SCRIPT_DIR/.." && pwd)
cd "$REPO"

ENV_FILE="${ENV_FILE:-$REPO/.env}"
ART="$REPO/docs/rollouts/esi-intel-feeds-pilot.md"
STATE="$REPO/docs/rollouts/.esi-intel-feeds-pilot.state"
LOG_WINDOW="${LOG_WINDOW:-10m}"

# Seed values from the runbook walkthrough (docs/sov-and-watchlist-feeds.md §
# "Main-server walkthrough", step 3) and the ticket Decisions paragraph.
SEED_ALLIANCES=(
  "Snuffed Out"
  "Shadow Cartel"
  "Minmatar Fleet Alliance"
  "Brotherhood of Spacers"
  "Legion of xXDEATHXx"
)
# The five seeded alliances' numeric ids, in the same order as SEED_ALLIANCES
# (verified live 2026-09-03; also listed in docs/sov-and-watchlist-feeds.md):
#   Snuffed Out 99004901, Shadow Cartel 495729389,
#   Minmatar Fleet Alliance 99011978, Brotherhood of Spacers 99007887,
#   Legion of xXDEATHXx 1411711376.
# These are our own constants (never operator input) so they are safe to
# interpolate into the step 3 and step 9 verification SELECTs.
SEED_ALLIANCE_IDS=(99004901 495729389 99011978 99007887 1411711376)
# All eight watchlist event kinds (four membership + four war); the option help
# in src/commands/watch_subscribe.rs and runbook §4 list them.
ALL_EVENT_KINDS="corp_joined,corp_left,member_delta,corp_changed_alliance,war_declared,war_ally_joined,war_retracted,war_finished"

# ── Evidence artifact and state helpers ───────────────────────────────────

now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

state_get() { # N -> prints recorded status or "-"
  [[ -f "$STATE" ]] || { printf -- '-'; return; }
  local v; v=$(grep -E "^$1=" "$STATE" | tail -n1) || true
  [[ -n "$v" ]] && printf '%s' "${v#*=}" || printf -- '-'
}

state_set() { # N STATUS
  local tmp; tmp=$(mktemp)
  [[ -f "$STATE" ]] && grep -vE "^$1=" "$STATE" > "$tmp" || true
  printf '%s=%s\n' "$1" "$2" >> "$tmp"
  mv "$tmp" "$STATE"
}

begin_entry() { # N "name"
  printf '\n### %s — Step %s · %s\n\n' "$(now_iso)" "$1" "$2" >> "$ART"
}
evid()      { printf -- '- %s\n' "$1" >> "$ART"; }
evid_code() { printf '\n```\n%s\n```\n\n' "$1" >> "$ART"; }
end_entry() { # N STATUS
  printf -- '\n- **Result: %s**\n' "$2" >> "$ART"
  state_set "$1" "$2"
  case "$2" in
    PASS|DONE) say "recorded ${GREEN}$2${RESET} for step $1 → $ART" ;;
    FAIL) warn "recorded FAIL for step $1 — go-live is paused until this gate passes; re-run this step after fixing the cause" ;;
    *) warn "recorded $2 for step $1 — re-run this step later" ;;
  esac
}

# gate_prompt N "gate" — ask the operator to sign the machine + human evidence
# off as PASS; anything else records PAUSED (a re-runnable pause, not an abort).
gate_prompt() { # N "label"
  if confirm "Record step $1 ($2) as PASS?"; then end_entry "$1" PASS
  elif confirm "Record it as FAIL (a failed gate that pauses go-live)?"; then end_entry "$1" FAIL
  else end_entry "$1" PAUSED; fi
}

# require_snowflake VAR "Label" N — validate that $VAR holds a plain numeric
# Discord id (a "snowflake"), stripping any surrounding whitespace in place
# first. Operator-entered ids (freshly typed, or reloaded as the .env default
# on a resume) are otherwise interpolated straight into psql -c SQL, which runs
# a whole batch — so a pasted mention like `<#123>` or a string containing
# `"); DELETE FROM ...` could run DML silently. On failure this warns, records
# the already-open evidence entry N as PAUSED (a re-runnable pause, not an
# abort), and returns non-zero so the caller aborts BEFORE any interpolation.
# Call it immediately after the id is captured and the entry is opened.
require_snowflake() { # VAR "Label" N
  local var="$1" label="$2" entry="${3:-}" value
  value="${!var}"
  value="${value#"${value%%[![:space:]]*}"}"   # strip leading whitespace
  value="${value%"${value##*[![:space:]]}"}"   # strip trailing whitespace
  printf -v "$var" '%s' "$value"               # write the stripped value back
  if [[ ! "$value" =~ ^[0-9]{1,20}$ ]]; then
    warn "$label must be a plain numeric Discord id (Developer Mode → Copy ID)"
    if [[ -n "$entry" ]]; then
      evid "$label rejected: not a plain numeric Discord id — step aborted before any query"
      end_entry "$entry" PAUSED
    fi
    return 1
  fi
  return 0
}

# ── PostgreSQL access (READ-ONLY; graceful degradation) ───────────────────
#
# Primary target is the live Compose database (the pilot runs on the existing
# production Compose instance). If Compose is unreachable, fall back to a
# psql + CONTRACT_TEST_DATABASE_URL connection when that variable is set (used
# for dry-running the wizard's checks); otherwise every DB check degrades
# with a clear message and a non-zero return.

DB_MODE=""   # compose | url | none

db_detect() {
  if command -v docker >/dev/null 2>&1 \
     && docker compose ps postgres 2>/dev/null | grep -q "Up"; then
    DB_MODE=compose; return 0
  fi
  if command -v psql >/dev/null 2>&1 && [[ -n "${CONTRACT_TEST_DATABASE_URL:-}" ]]; then
    DB_MODE=url; return 0
  fi
  DB_MODE=none; return 1
}

# q ARGS... — run psql with the given args against the detected database.
q() {
  case "$DB_MODE" in
    compose) docker compose exec -T postgres psql -U killbot_contracts -d killbot_contracts "$@" ;;
    url)     psql "$CONTRACT_TEST_DATABASE_URL" "$@" ;;
    *)       return 3 ;;
  esac
}

# require_db — ensure a database is reachable; print where we connected. On
# failure prints a clear message and returns non-zero so the caller can pause.
require_db() {
  db_detect || {
    warn "no database reachable: Compose 'postgres' is not Up and CONTRACT_TEST_DATABASE_URL is unset."
    note "start Compose (docker compose up -d postgres) or export CONTRACT_TEST_DATABASE_URL, then re-run this step."
    return 1
  }
  case "$DB_MODE" in
    compose) note "database: live Compose 'postgres' service (killbot_contracts)" ;;
    url)     note "database: CONTRACT_TEST_DATABASE_URL (fallback; wizard-check dry-run)" ;;
  esac
  return 0
}

# scalar "SQL" — one value, tuples-only. Empty string on DB error.
scalar() { q -At -c "$1" 2>/dev/null || true; }

# ── Log grep (READ-ONLY) ──────────────────────────────────────────────────

logs_grep() { # "regex"
  if [[ "$DB_MODE" != compose ]] && ! (command -v docker >/dev/null 2>&1); then
    warn "docker unavailable — capture the log lines manually"; return 1
  fi
  docker compose logs --since "$LOG_WINDOW" discordbot 2>/dev/null | grep -E "$1" || true
}

# env_present KEY — "present"/"absent"; NEVER prints the value (secret-safe).
env_present() {
  if [[ -f "$ENV_FILE" ]] && grep -qE "^$1=" "$ENV_FILE" && [[ -n "$(_existing "$1" || true)" ]]; then
    printf 'present'
  else
    printf 'absent'
  fi
}

# crontab_line — the exact hourly limiter-sample line the operator may add.
CRON_LINE="0 * * * * cd $REPO && ./scripts/esi-intel-feeds-pilot.sh sample >/dev/null 2>&1"

# ── Limiter sample (used by step 8 and the `sample` subcommand) ────────────

limiter_sample() {
  require_db || return 1
  local line
  line=$(scalar "SELECT format('sampled_at=%s group=%s remaining=%s used=%s error_remain=%s error_reset=%s pause_until=%s pacing=%s', now(), coalesce(rate_limit_group,'-'), coalesce(rate_limit_remaining,-1), coalesce(rate_limit_used,-1), coalesce(error_limit_remain,-1), coalesce(error_limit_reset,-1), coalesce(pause_until::text,'-'), pacing_active) FROM esi_collection_limiter_state WHERE limiter_scope = TRUE")
  if [[ -z "$line" ]]; then
    line="sampled_at=$(now_iso) (no esi_collection_limiter_state singleton row yet)"
  fi
  printf -- '- [limiter] %s\n' "$line" >> "$ART"
  say "appended limiter sample: $line"
}

# ══════════════════════════════════════════════════════════════════════════
# STEP FUNCTIONS — steps 0..11 from the ticket's D1.
# ══════════════════════════════════════════════════════════════════════════

step0_preflight() {
  stage "Step 0 · Preflight"
  say "Pin the commit and confirm the Compose stack and .env before any change."
  local head cfg ps
  head=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
  say "pinned commit: $head"
  if command -v docker >/dev/null 2>&1; then
    if docker compose config --quiet 2>/tmp/esi-pilot-cfg.$$; then cfg="docker compose config --quiet: OK"; else cfg="docker compose config --quiet: FAILED"; fi
    ps=$(docker compose ps 2>/dev/null || echo "docker compose ps unavailable")
  else
    cfg="docker not installed"; ps="docker not installed"
  fi
  rm -f /tmp/esi-pilot-cfg.$$
  say "$cfg"
  printf '%s\n' "$ps"
  say "env presence (values never printed):"
  local cdb wbu wm wk
  cdb=$(env_present CONTRACT_DATABASE_URL)
  wbu=$(env_present WANDERER_BASE_URL); wm=$(env_present WANDERER_MAP); wk=$(env_present WANDERER_MAP_API_KEY)
  say "  CONTRACT_DATABASE_URL: $cdb (feeds only start when set — runbook § Configuration and startup)"
  say "  WANDERER_BASE_URL: $wbu · WANDERER_MAP: $wm · WANDERER_MAP_API_KEY: $wk (all three needed for chain; step 10)"
  begin_entry 0 "Preflight"
  evid "pinned commit: \`$head\`"
  evid "$cfg"
  evid_code "$ps"
  evid "CONTRACT_DATABASE_URL: $cdb; WANDERER_BASE_URL: $wbu; WANDERER_MAP: $wm; WANDERER_MAP_API_KEY: $wk"
  if [[ "$cdb" != present ]]; then warn "CONTRACT_DATABASE_URL absent — the feeds will not start."; fi
  gate_prompt 0 "preflight"
}

step1_backup() {
  stage "Step 1 · Backup (read-only pg_dump)"
  say "Take a full custom-format backup before the first start on the new build."
  say "This is the ONLY database write this wizard performs — and pg_dump is read-only for the DB."
  require_db || { begin_entry 1 "Backup"; evid "database unreachable — backup skipped"; end_entry 1 PAUSED; return; }
  if [[ "$DB_MODE" != compose ]]; then
    warn "backup requires the Compose 'postgres' service; it is not Up. Skipping."
    begin_entry 1 "Backup"; evid "Compose postgres not Up — backup skipped"; end_entry 1 PAUSED; return
  fi
  local default_path="$REPO/backups/esi-intel-feeds-predeploy-$(date -u +%Y%m%dT%H%M%SZ).dump"
  local BACKUP_PATH
  ask BACKUP_PATH "Confirm the backup path [$default_path]:"
  [[ -z "$BACKUP_PATH" ]] && BACKUP_PATH="$default_path"
  mkdir -p "$(dirname "$BACKUP_PATH")"
  say "running: docker compose exec -T postgres pg_dump -U killbot_contracts -d killbot_contracts -Fc"
  if ! docker compose exec -T postgres pg_dump -U killbot_contracts -d killbot_contracts -Fc > "$BACKUP_PATH"; then
    warn "pg_dump failed."; begin_entry 1 "Backup"; evid "pg_dump failed for $BACKUP_PATH"; end_entry 1 FAIL; return
  fi
  chmod 600 "$BACKUP_PATH"
  local size sha entries
  size=$(wc -c < "$BACKUP_PATH" | tr -d ' ')
  if command -v shasum >/dev/null 2>&1; then sha=$(shasum -a 256 "$BACKUP_PATH" | awk '{print $1}')
  elif command -v sha256sum >/dev/null 2>&1; then sha=$(sha256sum "$BACKUP_PATH" | awk '{print $1}')
  else sha="(no sha256 tool)"; fi
  if command -v pg_restore >/dev/null 2>&1; then
    entries=$(pg_restore --list "$BACKUP_PATH" 2>/dev/null | grep -cvE '^(;|$)' || true)
  else
    entries=$(docker compose exec -T postgres pg_restore --list < "$BACKUP_PATH" 2>/dev/null | grep -cvE '^(;|$)' || true)
  fi
  say "path: $BACKUP_PATH"
  say "size: $size bytes · SHA-256: $sha · pg_restore --list entries: $entries"
  begin_entry 1 "Backup"
  evid "path: \`$BACKUP_PATH\` (custom archive, mode 0600)"
  evid "size: $size bytes"
  evid "SHA-256: \`$sha\`"
  evid "pg_restore --list entries: $entries"
  gate_prompt 1 "backup"
}

step2_deploy() {
  stage "Step 2 · Deploy and verify start-up"
  warn "The wizard does NOT deploy. You run the deploy; the wizard verifies."
  step "In a separate shell, from $REPO, run: docker compose up --build -d discordbot"
  pause "Press Enter once the new discordbot container is up."
  begin_entry 2 "Deploy and start-up verification"
  require_db || { evid "database unreachable — migration count unverified"; end_entry 2 PAUSED; return; }
  local mig
  mig=$(scalar "SELECT count(*) FROM _sqlx_migrations")
  say "migration count (_sqlx_migrations): ${mig:-unknown} (expected 33)"
  evid "migration count (_sqlx_migrations): ${mig:-unknown} (expected 33)"
  say "start-up lines (docker compose logs --since $LOG_WINDOW discordbot):"
  local startup
  startup=$(logs_grep "sov campaign feed started|watchlist feed started|Loaded stargate graph" || true)
  printf '%s\n' "${startup:-  (none found in window)}"
  evid_code "${startup:-(no start-up lines found in the $LOG_WINDOW window)}"
  gate_prompt 2 "deploy"
}

step3_seed() {
  stage "Step 3 · Seed the watchlist (five alliances, by full name)"
  say "Run these in any channel of the server (the watchlist is server-wide):"
  local a
  for a in "${SEED_ALLIANCES[@]}"; do step "/watch add kind:alliance ticker:$a"; done
  step "/watch list"
  pause "Press Enter after the five /watch add replies confirm the resolved names, and /watch list shows them."
  local GUILD
  ask PILOT_GUILD_ID "Enter the guild (server) id you seeded:"
  GUILD="$PILOT_GUILD_ID"
  begin_entry 3 "Seed watchlist"
  require_snowflake GUILD "guild id" 3 || return
  evid "guild id: $GUILD"
  require_db || { evid "database unreachable — seed count unverified"; end_entry 3 PAUSED; return; }
  local out present ids_values
  ids_values=$(printf '(%s),' "${SEED_ALLIANCE_IDS[@]}"); ids_values="${ids_values%,}"
  out=$(q -c "SELECT kind, count(*) FROM watchlist_entities WHERE guild_id = ${GUILD} GROUP BY kind ORDER BY kind" 2>&1 || true)
  present=$(q -c "SELECT a.entity_id, (e.entity_id IS NOT NULL) AS present FROM (VALUES $ids_values) AS a(entity_id) LEFT JOIN watchlist_entities e ON e.entity_id = a.entity_id AND e.kind = 'alliance' AND e.guild_id = ${GUILD} ORDER BY a.entity_id" 2>&1 || true)
  say "watchlist_entities for guild $GUILD (expect exactly 5 alliance rows):"
  printf '%s\n' "$out"
  say "seeded alliance presence for guild $GUILD (expect present=t for all five):"
  printf '%s\n' "$present"
  evid_code "watchlist_entities by kind:
$out

seeded alliance presence (expect all five entity_ids present=t, kind=alliance):
$present"
  gate_prompt 3 "seed"
}

step4_subscriptions() {
  stage "Step 4 · Sandbox subscriptions (#sandbox, no role)"
  say "In #sandbox, run (copied from the runbook walkthrough, role omitted for the sandbox):"
  step "/watch_subscribe name:sandbox-all event_kinds:$ALL_EVENT_KINDS"
  step "/sov_subscribe name:reachable-timers filter:{\"root\":{\"and\":[{\"condition\":{\"vulnerable_within\":{\"hours\":12}}},{\"condition\":{\"reachable\":{\"max_jumps\":11,\"allow_frigate_holes\":false}}}]}} tminus_marks:120,30"
  step "/sov_subscribe name:hostile-tz filter:{\"root\":{\"condition\":{\"defender\":{\"watchlist\":true}}}} tz_shift_enabled:true"
  pause "Press Enter after the three subscribe replies confirm."
  local CH
  ask PILOT_SANDBOX_CHANNEL_ID "Enter the #sandbox channel id:"
  CH="$PILOT_SANDBOX_CHANNEL_ID"
  begin_entry 4 "Sandbox subscriptions"
  require_snowflake CH "#sandbox channel id" 4 || return
  evid "#sandbox channel id: $CH"
  require_db || { evid "database unreachable — subscription rows unverified"; end_entry 4 PAUSED; return; }
  local ws ss
  ws=$(q -c "SELECT name, event_kinds, role_id FROM watchlist_subscriptions WHERE channel_id = ${CH}" 2>&1 || true)
  ss=$(q -c "SELECT name, role_id, options FROM sov_subscriptions WHERE channel_id = ${CH}" 2>&1 || true)
  say "watchlist_subscriptions (expect 1 row, role_id null):"; printf '%s\n' "$ws"
  say "sov_subscriptions (expect 2 rows, role_id null):"; printf '%s\n' "$ss"
  evid_code "watchlist_subscriptions:
$ws

sov_subscriptions:
$ss"
  say "Now run /sov_timers in #sandbox and paste its output as the day-0 board record."
  local TIMERS=""
  say "Paste /sov_timers output; end with a single line 'EOF':"
  local ln
  while IFS= read -r ln; do [[ "$ln" == "EOF" ]] && break; TIMERS+="$ln"$'\n'; done
  evid "/sov_timers day-0 capture (operator-pasted):"
  evid_code "${TIMERS:-(none pasted)}"
  gate_prompt 4 "sandbox subscriptions"
}

step5_gate_g1() {
  stage "Step 5 · Gate G1 (start-up)"
  say "G1: both runtimes' start-up lines present; sov/watchlist ESI progress reports within two cycles; stargate graph loaded; sandbox subscriptions listed."
  begin_entry 5 "Gate G1 — start-up"
  require_db || { evid "database unreachable — health snapshot unverified"; end_entry 5 PAUSED; return; }
  local health
  health=$(q -c "SELECT check_key, status, observed_at, evidence FROM health_check_results WHERE check_key IN ('sov_esi_progress','watchlist_esi_progress','sov_chain_progress','sov_permanent_delivery_failure','watchlist_permanent_delivery_failure') ORDER BY check_key" 2>&1 || true)
  say "persisted health snapshot (health_check_results — the five feed keys):"
  printf '%s\n' "$health"
  evid_code "$health"
  local sg
  sg=$(logs_grep "Loaded stargate graph|sov campaign feed started" || true)
  say "stargate graph / feed-start log line:"; printf '%s\n' "${sg:-  (none in window)}"
  evid_code "${sg:-(no stargate graph line found in the $LOG_WINDOW window)}"
  gate_prompt 5 "G1 start-up"
}

step6_gate_g2() {
  stage "Step 6 · Gate G2 (day 1)"
  say "G2: watchlist baselines silent (zero watchlist_deliveries); every 'appeared' alert corresponds to a campaign in /sov_timers and ESI campaigns."
  begin_entry 6 "Gate G2 — day 1"
  require_db || { evid "database unreachable — day-1 counts unverified"; end_entry 6 PAUSED; return; }
  local wd sd
  wd=$(scalar "SELECT count(*) FROM watchlist_deliveries")
  sd=$(q -c "SELECT stage, status, count(*) FROM sov_alert_deliveries GROUP BY stage, status ORDER BY stage, status" 2>&1 || true)
  say "watchlist_deliveries count (expect 0): ${wd:-unknown}"
  say "sov_alert_deliveries by stage/status:"; printf '%s\n' "$sd"
  evid "watchlist_deliveries count (expect 0): ${wd:-unknown}"
  evid_code "sov_alert_deliveries by stage/status:
$sd"
  say "Human check: does every 'appeared' alert in #sandbox match a campaign in /sov_timers and GET /sovereignty/campaigns/?"
  local PARITY
  ask G2_PARITY "Record the /sov_timers vs campaigns parity result (e.g. 'match, 3 campaigns' or 'no campaigns yet'):"
  PARITY="$G2_PARITY"
  evid "sov_timers vs campaigns parity (operator): $PARITY"
  gate_prompt 6 "G2 day 1"
}

step7_gate_g3() {
  stage "Step 7 · Gate G3 (restart — run on day 2 and again on day 5)"
  say "G3: after each restart, zero duplicate deliveries over both delivery tables (grouped by their dedup keys), and prepared rows drained."
  local DAY
  ask G3_DAY "Which restart is this? (2 or 5):"
  DAY="$G3_DAY"
  warn "The wizard does NOT restart. You restart; the wizard verifies."
  step "In a separate shell, from $REPO, run: docker compose restart discordbot"
  pause "Press Enter once the container is back up."
  begin_entry 7 "Gate G3 — restart day ${DAY:-?}"
  local rec
  rec=$(logs_grep "sov campaign feed started|sov campaign feed reconnected|watchlist feed started|watchlist feed reconnected" || true)
  say "post-restart start-up/reconnect lines:"; printf '%s\n' "${rec:-  (none in window)}"
  evid_code "${rec:-(no start-up/reconnect lines found in the $LOG_WINDOW window)}"
  require_db || { evid "database unreachable — duplicate/prepared checks unverified"; end_entry 7 PAUSED; return; }
  local sovdup watchdup prep
  sovdup=$(q -c "SELECT guild_id, channel_id, subscription_name, subject_kind, subject_id, stage, count(*) FROM sov_alert_deliveries GROUP BY 1,2,3,4,5,6 HAVING count(*) > 1" 2>&1 || true)
  watchdup=$(q -c "SELECT guild_id, channel_id, subscription_name, event_kind, entity_id, evidence_key, count(*) FROM watchlist_deliveries GROUP BY 1,2,3,4,5,6 HAVING count(*) > 1" 2>&1 || true)
  prep=$(scalar "SELECT (SELECT count(*) FROM sov_alert_deliveries WHERE status='prepared') AS sov_prepared, (SELECT count(*) FROM watchlist_deliveries WHERE status='prepared') AS watch_prepared")
  say "sov duplicate-delivery rows (expect empty):"; printf '%s\n' "$sovdup"
  say "watchlist duplicate-delivery rows (expect empty):"; printf '%s\n' "$watchdup"
  say "prepared rows sov|watch (expect 0|0 after drain): ${prep:-unknown}"
  evid_code "sov duplicates (expect empty):
$sovdup

watchlist duplicates (expect empty):
$watchdup

prepared rows (sov|watch, expect 0|0): ${prep:-unknown}"
  gate_prompt 7 "G3 restart day ${DAY:-?}"
}

step8_limiter() {
  stage "Step 8 · Limiter sampling (install / sample now / uninstall)"
  say "Take one limiter sample now, and manage the hourly cron sample yourself (the wizard never edits cron silently)."
  limiter_sample
  begin_entry 8 "Limiter sampling"
  evid "took one 'sample now' row (see the [limiter] lines in this artifact)."
  say "To collect an hourly sample for the pilot's duration, add this crontab line (crontab -e):"
  printf '  %s%s%s\n' "$BOLD" "$CRON_LINE" "$RESET"
  evid "crontab line to add: \`$CRON_LINE\`"
  warn "REMOVAL (do this at the end of the pilot): run 'crontab -e' and delete the line above."
  evid "removal at pilot end: 'crontab -e' and delete that line."
  gate_prompt 8 "limiter sampling"
}

step9_gate_g4() {
  stage "Step 9 · Gate G4 (day 7)"
  say "G4: ≥1 real watchlist event delivered exactly once; member snapshots ≥6.5 days old per seeded alliance; limiter never paused for the new collectors; /sov_timers parity re-checked; Dotlan click-check; tickets 08–10 demos recorded."
  begin_entry 9 "Gate G4 — day 7"
  require_db || { evid "database unreachable — day-7 counts unverified"; end_entry 9 PAUSED; return; }
  local ekind dup snap snap_fail ids_values
  ids_values=$(printf '(%s),' "${SEED_ALLIANCE_IDS[@]}"); ids_values="${ids_values%,}"
  ekind=$(q -c "SELECT event_kind, status, count(*) FROM watchlist_deliveries GROUP BY event_kind, status ORDER BY event_kind, status" 2>&1 || true)
  dup=$(q -c "SELECT guild_id, channel_id, subscription_name, event_kind, entity_id, evidence_key, count(*) FROM watchlist_deliveries GROUP BY 1,2,3,4,5,6 HAVING count(*) > 1" 2>&1 || true)
  # G4 requires member-delta history for EVERY seeded alliance, so scope to the
  # five seeded ids and kind='alliance' (not a blanket GROUP BY across all
  # observed entities). One row per seeded id via a LEFT JOIN so a missing
  # alliance still shows (snapshots=0, pass=f). pass=t needs the oldest
  # snapshot to be ≥6.5 days (156h) old.
  snap=$(q -c "SELECT a.entity_id, count(s.observed_at) AS snapshots, min(s.observed_at) AS oldest, max(s.observed_at) AS newest, (count(s.observed_at) > 0 AND min(s.observed_at) <= now() - interval '156 hours') AS pass FROM (VALUES $ids_values) AS a(entity_id) LEFT JOIN watchlist_member_snapshots s ON s.entity_id = a.entity_id AND s.entity_kind = 'alliance' GROUP BY a.entity_id ORDER BY a.entity_id" 2>&1 || true)
  snap_fail=$(scalar "SELECT count(*) FROM (SELECT a.entity_id FROM (VALUES $ids_values) AS a(entity_id) LEFT JOIN watchlist_member_snapshots s ON s.entity_id = a.entity_id AND s.entity_kind = 'alliance' GROUP BY a.entity_id HAVING NOT (count(s.observed_at) > 0 AND min(s.observed_at) <= now() - interval '156 hours')) f")
  say "delivered events by event_kind (expect ≥1 real event delivered once):"; printf '%s\n' "$ekind"
  say "duplicate-delivery rows (expect empty):"; printf '%s\n' "$dup"
  say "member-delta history per seeded alliance (pass=t needs oldest snapshot ≥156h / 6.5d old):"; printf '%s\n' "$snap"
  evid_code "delivered by event_kind:
$ekind

duplicates (expect empty):
$dup

member-delta history per seeded alliance (kind=alliance; pass needs oldest ≤ now()-156h):
$snap"
  if [[ "$snap_fail" =~ ^[0-9]+$ ]] && (( snap_fail > 0 )); then
    warn "G4 member-delta history check FAILED: $snap_fail of ${#SEED_ALLIANCE_IDS[@]} seeded alliance(s) lack ≥6.5 days of snapshots."
    evid "G4 member-delta history machine check: FAIL ($snap_fail of ${#SEED_ALLIANCE_IDS[@]} seeded alliances without ≥156h of 'alliance' snapshots)"
    end_entry 9 FAIL
    return
  fi
  evid "G4 member-delta history machine check: PASS (all ${#SEED_ALLIANCE_IDS[@]} seeded alliances have ≥156h of 'alliance' snapshots)"
  # Limiter sample summary from the artifact's [limiter] lines.
  local minrem paused
  minrem=$(awk -F'remaining=' '/^- \[limiter\]/{split($2,a," "); if(a[1]!="" && a[1]!=-1){print a[1]}}' "$ART" 2>/dev/null | sort -n | head -1)
  paused=$(grep -c 'pause_until=[0-9]' "$ART" 2>/dev/null || true)
  say "limiter samples: min remaining=${minrem:-none captured}; rows with a future pause set=${paused:-0}"
  evid "limiter sample summary: min remaining=${minrem:-none}; sample rows showing a pause_until timestamp=${paused:-0}"
  local DEMO
  ask G4_DOTLAN "Dotlan numeric corporation URL click-check from a real embed (result):"
  evid "Dotlan click-check (operator): ${G4_DOTLAN:-pending}"
  ask G4_DEMOS "Deferred tickets 08–10 demo items recorded (summary):"
  evid "tickets 08–10 demos (operator): ${G4_DEMOS:-pending}"
  gate_prompt 9 "G4 day 7"
}

step10_gate_g5() {
  stage "Step 10 · Gate G5 (Wanderer chain)"
  say "G5: after the WANDERER_* variables are set and the bot restarted, 'sov chain reachability enabled' logs, sov_chain_progress reports, and one chain-driven 'reachable' transition is observed and delivered once."
  say "env presence (values never printed):"
  say "  WANDERER_BASE_URL: $(env_present WANDERER_BASE_URL) · WANDERER_MAP: $(env_present WANDERER_MAP) · WANDERER_MAP_API_KEY: $(env_present WANDERER_MAP_API_KEY)"
  step "Set the three WANDERER_* variables in .env yourself, then: docker compose up --build -d discordbot (or restart)."
  pause "Press Enter once the bot is back up with the chain configured."
  begin_entry 10 "Gate G5 — chain"
  evid "WANDERER_BASE_URL: $(env_present WANDERER_BASE_URL); WANDERER_MAP: $(env_present WANDERER_MAP); WANDERER_MAP_API_KEY: $(env_present WANDERER_MAP_API_KEY)"
  local chain
  chain=$(logs_grep "sov chain reachability enabled|sov chain reachability reconnected" || true)
  say "chain-enabled log line:"; printf '%s\n' "${chain:-  (none in window)}"
  evid_code "${chain:-(no chain-enabled line found in the $LOG_WINDOW window)}"
  require_db || { evid "database unreachable — sov_chain_progress unverified"; end_entry 10 PAUSED; return; }
  local cp
  cp=$(q -c "SELECT check_key, status, observed_at, evidence FROM health_check_results WHERE check_key = 'sov_chain_progress'" 2>&1 || true)
  say "sov_chain_progress health key:"; printf '%s\n' "$cp"
  evid_code "$cp"
  ask G5_TRANSITION "Observed chain-driven 'reachable' transition delivered once (describe):"
  evid "reachable transition (operator): ${G5_TRANSITION:-pending}"
  gate_prompt 10 "G5 chain"
}

step11_golive() {
  stage "Step 11 · Go-live (three production channels)"
  say "Create the three production channels' subscriptions exactly as the runbook lists them, with the roamers role filled in."
  say "Verify one NON-PINGING cycle in each channel BEFORE adding role. Production invocations from the runbook walkthrough §4:"
  step "#sov-timers: /sov_subscribe name:reachable-timers filter:{\"root\":{\"and\":[{\"condition\":{\"vulnerable_within\":{\"hours\":12}}},{\"condition\":{\"reachable\":{\"max_jumps\":11,\"allow_frigate_holes\":false}}}]}} tminus_marks:120,30 role:@Roamers"
  step "#hostile-wars: /watch_subscribe name:hostile-wars event_kinds:war_declared,war_ally_joined,war_retracted,war_finished role:@HostileWars"
  step "#hostile-intel: /watch_subscribe name:hostile-intel event_kinds:corp_joined,corp_left,member_delta,corp_changed_alliance"
  step "#hostile-intel: /sov_subscribe name:hostile-tz filter:{\"root\":{\"condition\":{\"defender\":{\"watchlist\":true}}}} tz_shift_enabled:true"
  note "@Roamers / @HostileWars are the runbook's role placeholders — substitute the real roamers role."
  if ! confirm "Confirmed one non-pinging cycle per channel before adding any role?"; then
    warn "Add role only after a clean non-pinging cycle. Recording PAUSED."
    begin_entry 11 "Go-live"; evid "non-pinging cycle not yet confirmed"; end_entry 11 PAUSED; return
  fi
  local STCH WCH ICH
  ask GOLIVE_SOV_CHANNEL_ID "#sov-timers channel id:"; STCH="$GOLIVE_SOV_CHANNEL_ID"
  ask GOLIVE_WARS_CHANNEL_ID "#hostile-wars channel id:"; WCH="$GOLIVE_WARS_CHANNEL_ID"
  ask GOLIVE_INTEL_CHANNEL_ID "#hostile-intel channel id:"; ICH="$GOLIVE_INTEL_CHANNEL_ID"
  begin_entry 11 "Go-live"
  require_snowflake STCH "#sov-timers channel id" 11 || return
  require_snowflake WCH "#hostile-wars channel id" 11 || return
  require_snowflake ICH "#hostile-intel channel id" 11 || return
  evid "channels — #sov-timers: $STCH · #hostile-wars: $WCH · #hostile-intel: $ICH"
  require_db || { evid "database unreachable — final subscription rows unverified"; end_entry 11 PAUSED; return; }
  local rows
  rows=$(q -At -c "SELECT json_agg(r) FROM (
    SELECT 'sov' AS feed, guild_id, channel_id, name, role_id, options FROM sov_subscriptions WHERE channel_id IN (${STCH}, ${ICH})
    UNION ALL
    SELECT 'watchlist' AS feed, guild_id, channel_id, name, role_id, to_jsonb(event_kinds) FROM watchlist_subscriptions WHERE channel_id IN (${WCH}, ${ICH})
  ) r" 2>&1 || true)
  say "final production subscription rows (JSON):"; printf '%s\n' "$rows"
  evid_code "$rows"
  warn "Reminder: remove the hourly limiter-sample crontab line now (step 8's removal)."
  evid "handoff: pilot complete; write the member announcement only after this; re-triage tickets 12/13 against the limiter samples."
  ask GOLIVE_HANDOFF "Handoff note (freeform):"
  evid "handoff note (operator): ${GOLIVE_HANDOFF:-pending}"
  gate_prompt 11 "go-live"
}

# ── Dispatch: menu, single step, or `sample` subcommand ───────────────────

STEP_NAMES=(
  "Preflight"
  "Backup (read-only pg_dump)"
  "Deploy and verify start-up"
  "Seed the watchlist"
  "Sandbox subscriptions"
  "Gate G1 — start-up"
  "Gate G2 — day 1"
  "Gate G3 — restart (days 2 and 5)"
  "Limiter sampling"
  "Gate G4 — day 7"
  "Gate G5 — chain"
  "Go-live"
)

run_step() {
  case "$1" in
    0) step0_preflight ;;  1) step1_backup ;;      2) step2_deploy ;;
    3) step3_seed ;;       4) step4_subscriptions ;; 5) step5_gate_g1 ;;
    6) step6_gate_g2 ;;    7) step7_gate_g3 ;;     8) step8_limiter ;;
    9) step9_gate_g4 ;;    10) step10_gate_g5 ;;   11) step11_golive ;;
    *) warn "unknown step: $1"; return 1 ;;
  esac
}

menu() {
  banner "ESI intel feeds — seven-day pilot & go-live"
  while true; do
    stage "Menu — pick a step to run"
    say "State: $STATE"
    say "Artifact: $ART"
    printf '\n'
    local i
    for i in "${!STEP_NAMES[@]}"; do
      printf '  %s%2s%s  %-34s [%s]\n' "$BOLD" "$i" "$RESET" "${STEP_NAMES[$i]}" "$(state_get "$i")"
    done
    printf '  %s q%s  quit\n\n' "$BOLD" "$RESET"
    local choice
    ask MENU_CHOICE "Step number (0-11) or q:"
    choice="$MENU_CHOICE"
    [[ "$choice" == q || "$choice" == Q ]] && break
    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 0 && choice <= 11 )); then
      run_step "$choice" || true
      pause "Press Enter to return to the menu."
    else
      warn "enter 0-11 or q."
    fi
  done
  finish
}

main() {
  mkdir -p "$(dirname "$ART")"
  if [[ ! -f "$ART" ]]; then
    warn "artifact $ART is missing — create the skeleton first (see the ticket)."; exit 1
  fi
  case "${1:-}" in
    "")        menu ;;
    sample)    limiter_sample ;;
    0|1|2|3|4|5|6|7|8|9|10|11) run_step "$1" ;;
    -h|--help) printf 'usage: %s [step 0-11 | sample]\n' "$(basename "$0")" ;;
    *)         warn "unknown argument: $1 (use a step 0-11, 'sample', or no argument for the menu)"; exit 2 ;;
  esac
}

main "$@"
