#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
umask 077

STATE_FILE=""
BUNDLE_FILE=""
VALUES_FILE=""
WORK_ENV_FILE=""
ENV_LOCK=""
CLIENT_MODE=""
CLIENT_ID=""
CLIENT_SECRET=""
PROBES_READY=false

cleanup() {
  [[ -n "$STATE_FILE" ]] && rm -f -- "$STATE_FILE"
  [[ -n "$BUNDLE_FILE" ]] && rm -f -- "$BUNDLE_FILE"
  [[ -n "$VALUES_FILE" ]] && rm -f -- "$VALUES_FILE"
  [[ -n "$WORK_ENV_FILE" ]] && rm -f -- "$WORK_ENV_FILE"
  [[ -n "$ENV_LOCK" ]] && rmdir -- "$ENV_LOCK" 2>/dev/null || true
}
trap cleanup EXIT

remove_env() {
  local key="$1" tmp
  [[ -f "$ENV_FILE" ]] || return 0
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
}

persist_values() {
  local original_env="$ENV_FILE" env_dir env_name env_key env_value
  env_dir=$(dirname "$original_env")
  env_name=$(basename "$original_env")
  ENV_LOCK="${original_env}.structure-resolver.lock"
  if ! mkdir "$ENV_LOCK" 2>/dev/null; then
    warn "another structure-resolver provisioning run owns $ENV_LOCK"
    return 1
  fi
  WORK_ENV_FILE=$(mktemp "${env_dir}/.${env_name}.structure-resolver.XXXXXX")
  [[ -f "$original_env" ]] && cp "$original_env" "$WORK_ENV_FILE"
  ENV_FILE="$WORK_ENV_FILE"
  while IFS=$'\t' read -r env_key env_value; do
    [[ -n "$env_key" ]] || continue
    write_env "$env_key" "$env_value"
  done < "$VALUES_FILE"
  if [[ "$CLIENT_MODE" == "existing" ]]; then
    remove_env STRUCTURE_RESOLVER_CLIENT_ID
    remove_env STRUCTURE_RESOLVER_CLIENT_SECRET
  fi
  chmod 600 "$WORK_ENV_FILE"
  mv "$WORK_ENV_FILE" "$original_env"
  WORK_ENV_FILE=""
  ENV_FILE="$original_env"
  rmdir "$ENV_LOCK"
  ENV_LOCK=""
}

banner "Structure resolver authorization"

stage "Preflight"
say "This provisions only the feature-gated structure resolver. Public contract collection stays unauthenticated."
step "Confirm this checkout has Rust/Cargo and that ENV_FILE points at the runtime environment file."
note "The wizard writes .env with mode 0600. .env is excluded from the Docker build context."
if [[ -n "$(_existing EVE_CLIENT_ID || true)" && -n "$(_existing EVE_CLIENT_SECRET || true)" ]]; then
  say "An existing EVE application credential pair is present; its values will not be displayed."
else
  warn "No complete existing EVE application credential pair is available in ENV_FILE."
fi
pause "Press Enter after confirming the runtime environment file."

stage "Application and registered redirect"
ask STRUCTURE_RESOLVER_REDIRECT_URI "Paste the exact registered redirect URI (no query or fragment):"
if [[ -n "$(_existing EVE_CLIENT_ID || true)" && -n "$(_existing EVE_CLIENT_SECRET || true)" ]] && confirm "Does the existing app list this exact redirect and esi-universe.read_structures.v1 in its Developer Portal configuration?"; then
  CLIENT_MODE=existing
  ask EVE_CLIENT_ID "Confirm the existing EVE application client ID:"
  ask_secret EVE_CLIENT_SECRET "Confirm the existing EVE application client secret:"
  CLIENT_ID="$EVE_CLIENT_ID"
  CLIENT_SECRET="$EVE_CLIENT_SECRET"
else
  CLIENT_MODE=dedicated
  say "The existing application is incompatible or unavailable, so provision a resolver-only fallback application."
  open_url "https://developers.eveonline.com/applications"
  step "Create an Authentication & API Access application for the Structure Resolver."
  step "Register the exact redirect URI entered above and assign only esi-universe.read_structures.v1."
  step "Copy its client ID and reveal its client secret. Do not add it to GitHub Actions: this repository has no workflow that consumes it."
  ask STRUCTURE_RESOLVER_CLIENT_ID "Paste the dedicated resolver application client ID:"
  ask_secret STRUCTURE_RESOLVER_CLIENT_SECRET "Paste the dedicated resolver application client secret:"
  CLIENT_ID="$STRUCTURE_RESOLVER_CLIENT_ID"
  CLIENT_SECRET="$STRUCTURE_RESOLVER_CLIENT_SECRET"
fi

stage "Fresh authorization request"
STATE_FILE=$(mktemp)
AUTHORIZATION_URL=$(cargo run --quiet --bin structure_resolver_provision -- prepare --client-id "$CLIENT_ID" --redirect-uri "$STRUCTURE_RESOLVER_REDIRECT_URI" --state-file "$STATE_FILE")
say "The browser request has one scope only: esi-universe.read_structures.v1."
step "Authorize the dedicated resolver character, not an ordinary standings authorization."
open_url "$AUTHORIZATION_URL"
pause "Return here after EVE redirects the browser to the registered callback."

stage "Complete callback"
say "Copy the complete browser callback URI, including both code and state query parameters."
say "The callback is hidden because its one-time authorization code is sensitive."
ask_secret CALLBACK_URI "Paste the complete callback URI:"

stage "Exchange and signed claim validation"
BUNDLE_FILE=$(mktemp)
if ! printf '%s\n%s' "$CLIENT_SECRET" "$CALLBACK_URI" | cargo run --quiet --bin structure_resolver_provision -- authorize --client-id "$CLIENT_ID" --redirect-uri "$STRUCTURE_RESOLVER_REDIRECT_URI" --state-file "$STATE_FILE" --bundle-file "$BUNDLE_FILE" --env-file "$ENV_FILE" --client-mode "$CLIENT_MODE"; then
  warn "Authorization was not persisted. State, redirect, code exchange, signature, issuer, audience, expiry, character, and exact scope validation must all succeed."
  SKIPPED+=("Resolve the authorization error and re-run this wizard; no resolver settings were changed")
  finish
  exit 1
fi
say "The callback state was checked before code exchange; validated credentials remain in a 0600 temporary file until probes finish."

stage "Known structure probes"
ask KNOWN_STRUCTURE_IDS "Paste one or more known structure IDs, separated by commas:"
PROBE_OUTPUT=$(cargo run --quiet --bin structure_resolver_provision -- probe --bundle-file "$BUNDLE_FILE" --structure-ids "$KNOWN_STRUCTURE_IDS")
say "Known-probe coverage: $PROBE_OUTPUT"
case "$PROBE_OUTPUT" in
  full\ *)
    PROBES_READY=true
    say "Full means every supplied ID resolved. It does not establish universal structure access."
    ;;
  partial\ *)
    PROBES_READY=true
    warn "Partial means at least one supplied ID was denied. The resolver remains access-qualified, not universal."
    ;;
  denied\ *)
    warn "All supplied IDs were denied. The resolver will remain disabled."
    SKIPPED+=("Grant the dedicated character access to a known structure, then re-run the wizard")
    ;;
  *)
    warn "Probe coverage is indeterminate (network, token, or upstream failure). The resolver will remain disabled."
    SKIPPED+=("Resolve the indeterminate ESI/SSO condition, then re-run the wizard")
    ;;
esac

stage "Persist and enable"
if [[ "$PROBES_READY" != true ]]; then
  warn "No resolver environment values were persisted because known probes are not ready."
elif [[ "$PROBE_OUTPUT" == partial\ * ]] && ! confirm "Enable only access-qualified enrichment with this partial known-probe coverage?"; then
  SKIPPED+=("Review partial structure coverage before enabling the resolver")
else
  VALUES_FILE=$(mktemp)
  cargo run --quiet --bin structure_resolver_provision -- env-values --bundle-file "$BUNDLE_FILE" --values-file "$VALUES_FILE" --enabled true
  persist_values
  say "Restart the bot after this wizard so it loads the new resolver credential revision."
  note "A later rerun replaces the refresh token and advances the credential revision without duplicate keys."
fi

finish
